/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 * Modelo donde se mostrara los datos de una tarea.
 * @author miguelportatil
 */
public class ModeloTarea extends javax.swing.JPanel {

    /**
     * Creates new form ModeloTarea
     */
    private int id;
    private VistaPrincipal jFramePadre;
    public ModeloTarea(int id,VistaPrincipal jFramePadre) {
        this.id = id;
        this.jFramePadre = jFramePadre;
        initComponents();
        Image img= new ImageIcon(getClass().getResource("/imagen/delete.png")).getImage();
        ImageIcon img2=new ImageIcon(img.getScaledInstance(35,35,Image.SCALE_SMOOTH));
        jLabelPapelera.setIcon(img2);
    }

    public JLabel getjLabelDescripcion() {
        return jLabelDescripcion;
    }

    public void setjLabelDescripcion(JLabel jLabelDescripcion) {
        this.jLabelDescripcion = jLabelDescripcion;
    }

    public JLabel getjLabelFechaInicio() {
        return jLabelFechaInicio;
    }

    public void setjLabelFechaInicio(JLabel jLabelFechaInicio) {
        this.jLabelFechaInicio = jLabelFechaInicio;
    }

    public JLabel getjLabelNombre() {
        return jLabelNombre;
    }

    public void setjLabelNombre(JLabel jLabelNombre) {
        this.jLabelNombre = jLabelNombre;
    }

    public JLabel getjLabelNumDias() {
        return jLabelNumDias;
    }

    public void setjLabelNumDias(JLabel jLabelNumDias) {
        this.jLabelNumDias = jLabelNumDias;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelPapelera = new javax.swing.JLabel();
        jLabelNumDias = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 225));
        setMinimumSize(new java.awt.Dimension(400, 225));
        setPreferredSize(new java.awt.Dimension(400, 225));

        jLabelNombre.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre");

        jLabelDescripcion.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDescripcion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDescripcion.setText("AQUI VA LA DESCRIPCION que es muy pero que muy muy muy largo jajajaj");
        jLabelDescripcion.setToolTipText("");
        jLabelDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDescripcion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabelFechaInicio.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabelFechaInicio.setForeground(new java.awt.Color(153, 153, 153));
        jLabelFechaInicio.setText("FECHA");

        jLabelPapelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/delete.png"))); // NOI18N
        jLabelPapelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPapeleraMouseClicked(evt);
            }
        });

        jLabelNumDias.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelNumDias.setForeground(new java.awt.Color(96, 147, 191));
        jLabelNumDias.setText("0 dias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNumDias))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPapelera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNumDias))
                .addGap(34, 34, 34)
                .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPapelera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelDescripcion.getAccessibleContext().setAccessibleName("AQUI VA LA DESCRIPCION que \nes muy pero que muy muy \nmuy largo jajajaj");
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPapeleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPapeleraMouseClicked
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(jFramePadre, "¿Borrar tarea?");
        if(resultado == 0){
            int activo = jFramePadre.getTaskTime().getProyectoActivo();
            jFramePadre.getTaskTime().getProyectos().get(activo).deleteTarea(id);
            jFramePadre.getPanelTareas().limpiarTareas();
            jFramePadre.getPanelTareas().generarTareas();
            
            //REFRESCA LAS FECHAS Y CUANTOS TAREAS LE QUEDAN AL PROYECTO
            jFramePadre.getPanelProyecto().setTareas(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getTareas().size());
            jFramePadre.getPanelProyecto().setjTextFieldFechaInicio(" "  + jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getFechaInicio().toString());
            jFramePadre.getPanelProyecto().setjTextFieldFechaFin(" "  + jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getFechaFin().toString());
        }
        
    }//GEN-LAST:event_jLabelPapeleraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumDias;
    private javax.swing.JLabel jLabelPapelera;
    // End of variables declaration//GEN-END:variables
}
