/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.CRM;

/**
 * Contenedor con el logo de la aplicación y cuatro botones alta de tarea , alta de proyecto ,
 * guardar y salir
 * 
 * @author miguelportatil
 */
public class PanelLogo extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogo
     */
    VistaPrincipal jFramePadre;
    public PanelLogo() {
        initComponents();
        setButtonIcon();
    }

    public VistaPrincipal getJFramePadre() {
        return jFramePadre;
    }

    public void setJFramePadre(VistaPrincipal jFramePadre) {
        this.jFramePadre = jFramePadre;
    }
    
    /**
     * Reescala las imagenes de cada botón para poder tener una buena visualización.
     */
    private void setButtonIcon() {
        Image img= new ImageIcon(getClass().getResource("/imagen/reloj.png")).getImage();
        ImageIcon img2=new ImageIcon(img.getScaledInstance(160,160,Image.SCALE_SMOOTH));
        jLabelLogo.setIcon(img2);
        
        Image imgAddTarea= new ImageIcon(getClass().getResource("/imagen/add.png")).getImage();
        ImageIcon imgAddBtTarea=new ImageIcon(imgAddTarea.getScaledInstance(35,35,Image.SCALE_SMOOTH));
        jButtonAddTarea.setIcon(imgAddBtTarea);
        jButtonAddTarea.setText("");
        
        Image imgAddProyecto= new ImageIcon(getClass().getResource("/imagen/folder.png")).getImage();
        ImageIcon imgAddBtProyecto=new ImageIcon(imgAddProyecto.getScaledInstance(35,35,Image.SCALE_SMOOTH));
        jButtonAddProyecto.setIcon(imgAddBtProyecto);
        jButtonAddProyecto.setText("");
        
        Image imgAddGuardar= new ImageIcon(getClass().getResource("/imagen/save.png")).getImage();
        ImageIcon imgAddBtGuardar=new ImageIcon(imgAddGuardar.getScaledInstance(35,35,Image.SCALE_SMOOTH));
        jButtonGuardar.setIcon(imgAddBtGuardar);
        jButtonGuardar.setText("");
        
        Image imgAddSalir= new ImageIcon(getClass().getResource("/imagen/exit.png")).getImage();
        ImageIcon imgAddBtSalir=new ImageIcon(imgAddSalir.getScaledInstance(35,35,Image.SCALE_SMOOTH));
        jButtonSalir.setIcon(imgAddBtSalir);
        jButtonSalir.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jButtonAddProyecto = new javax.swing.JButton();
        jButtonAddTarea = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(340, 265));
        setMinimumSize(new java.awt.Dimension(340, 265));
        setPreferredSize(new java.awt.Dimension(340, 265));

        jButtonAddProyecto.setText("2");
        jButtonAddProyecto.setToolTipText("Añadir proyecto");
        jButtonAddProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProyectoActionPerformed(evt);
            }
        });

        jButtonAddTarea.setText("2");
        jButtonAddTarea.setToolTipText("Añadir tarea");
        jButtonAddTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTareaActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("2");
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("2");
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonAddProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAddProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        jFramePadre.getTaskTime().getGestionDatos().guardarProyectos(jFramePadre.getTaskTime().getProyectos());
        CRM.nuevoMensaje("Guardado realizado.");
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonAddProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProyectoActionPerformed
        // TODO add your handling code here:
        VentanaAddProyecto addProyecto = new VentanaAddProyecto(jFramePadre, true);
        addProyecto.setVisible(true);
    }//GEN-LAST:event_jButtonAddProyectoActionPerformed

    private void jButtonAddTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTareaActionPerformed
        // TODO add your handling code here:
        if(jFramePadre.getTaskTime().getProyectos()==null || jFramePadre.getTaskTime().getProyectos().size()==0){
            JOptionPane.showMessageDialog(jFramePadre, "Crea antes un proyecto");
            CRM.nuevoMensaje("No existe ningun proyecto");
        }
        else{
            VentanaAddTarea addTarea = new VentanaAddTarea(jFramePadre, true);
            addTarea.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAddTareaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        CRM.nuevoMensaje("Saliendo");
        int salida = JOptionPane.showConfirmDialog(jFramePadre,"¿Quieres guardar antes de salir?","Guardar",JOptionPane.OK_CANCEL_OPTION);
        if(salida == 0){
            jFramePadre.getTaskTime().getGestionDatos().guardarProyectos(jFramePadre.getTaskTime().getProyectos());
        }
        System.exit(0);
        
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProyecto;
    private javax.swing.JButton jButtonAddTarea;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
