/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JFrame;

/**
 * Contenedor de los tres botones acerca de , proyectos y tareas
 * 
 * @author miguelportatil
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    VistaPrincipal jFramePadre;
    public PanelBotones() {
        initComponents();
    }

    public JFrame getJFramePadre() {
        return jFramePadre;
    }

    public void setJFramePadre(VistaPrincipal padre) {
        this.jFramePadre = padre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonProyectos = new javax.swing.JButton();
        jButtonAcerca = new javax.swing.JButton();
        jButtonTareas1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(132, 177, 217));
        setMinimumSize(new java.awt.Dimension(340, 449));
        setPreferredSize(new java.awt.Dimension(340, 449));

        jButtonProyectos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProyectos.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jButtonProyectos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonProyectos.setText("Proyectos");
        jButtonProyectos.setToolTipText("Listar proyectos");
        jButtonProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProyectosActionPerformed(evt);
            }
        });

        jButtonAcerca.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAcerca.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jButtonAcerca.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAcerca.setText("Acerca de");
        jButtonAcerca.setToolTipText("Acerda de");
        jButtonAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcercaActionPerformed(evt);
            }
        });

        jButtonTareas1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTareas1.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jButtonTareas1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTareas1.setText("Tareas");
        jButtonTareas1.setToolTipText("Listar tareas");
        jButtonTareas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTareas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAcerca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButtonProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButtonTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButtonAcerca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProyectosActionPerformed
        // TODO add your handling code here:
        jFramePadre.setVisibilityProyectos(true);
        jFramePadre.setVisibilityAcerca(false);
        jFramePadre.setVisibilityTareas(false);
    }//GEN-LAST:event_jButtonProyectosActionPerformed

    private void jButtonAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcercaActionPerformed
        // TODO add your handling code here:
        jFramePadre.setVisibilityProyectos(false);
        jFramePadre.setVisibilityAcerca(true);
        jFramePadre.setVisibilityTareas(false);
    }//GEN-LAST:event_jButtonAcercaActionPerformed

    private void jButtonTareas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTareas1ActionPerformed
        // TODO add your handling code here:
        jFramePadre.setVisibilityProyectos(false);
        jFramePadre.setVisibilityAcerca(false);
        jFramePadre.setVisibilityTareas(true);
        jFramePadre.getPanelTareas().generarTareas();
    }//GEN-LAST:event_jButtonTareas1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcerca;
    private javax.swing.JButton jButtonProyectos;
    private javax.swing.JButton jButtonTareas1;
    // End of variables declaration//GEN-END:variables
}
