/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.time.LocalDate;
import java.util.Collections;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import modelo.Tarea;
import util.Util;

/**
 * Contenedor que se encarga de pintar cada tarea.
 * @author miguelportatil
 */
public class PanelTareas extends javax.swing.JPanel {

    /**
     * Creates new form PanelTareas
     */
    GridBagConstraints c;
    VistaPrincipal jFramePadre;
    
    public PanelTareas() {
        initComponents();
        //jScrollPaneTareas.getViewport().setBackground(new Color(204,204,204));
        c = new GridBagConstraints();
        c.weightx=15; 
        c.insets=new Insets(20,20,20,20);
    }
    
    public void generarTareas(){
        try{
            int activo = jFramePadre.getTaskTime().getProyectoActivo();
            List<Tarea> tareas = jFramePadre.getTaskTime().getProyectos().get(activo).getTareas();
            Collections.sort(tareas);
            int y = 0;
            int x = 0;
            for(int i = 0;i<tareas.size();i++){
                ModeloTarea model = new ModeloTarea(i,jFramePadre);
                LocalDate fechaFin = tareas.get(i).getFechaFin();
                LocalDate now = LocalDate.now();
                int numDias = 0;
                if(fechaFin.isAfter(now)){
                    while(!fechaFin.equals(now.plusDays(numDias))){
                        numDias++;
                    }
                }
                
                model.getjLabelNumDias().setText(numDias+" dias");
                model.getjLabelNombre().setText(tareas.get(i).getNombre());
                model.getjLabelDescripcion().setText(tareas.get(i).getDescripcion());
                model.getjLabelDescripcion().setToolTipText(tareas.get(i).getDescripcion());
                model.getjLabelFechaInicio().setText(Util.ft.format(tareas.get(i).getFechaInicio()));
                
                
                Border line = null;
                switch(tareas.get(i).getImportancia()){
                    case ALTA:
                        line = BorderFactory.createLineBorder(Color.red);
                        break;
                    case MEDIA:
                        line = BorderFactory.createLineBorder(Color.orange);
                        break;
                    case BAJA:
                        line = BorderFactory.createLineBorder(Color.green);
                        break;
                    default:
                        line = BorderFactory.createLineBorder(Color.black);
                }
                    
                if(numDias==0){
                    model.getjLabelNumDias().setEnabled(false);
                    model.getjLabelNombre().setEnabled(false);
                    model.getjLabelDescripcion().setEnabled(false);
                    line = BorderFactory.createLineBorder(Color.black);
                }
                
                model.setBorder(line);
                c.gridx = x;
                c.gridy = y;
                jPanelTareas.add(model,c);
                x++;
                if(x==2){
                    y++;
                    x=0;
                }
            }
        }catch(NullPointerException e){
        }catch(IndexOutOfBoundsException ioobe){}
    }
    
    public void limpiarTareas(){
        jPanelTareas = new JPanel();
        jPanelTareas.setLayout(new java.awt.GridBagLayout());
        jPanelTareas.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTareas.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPaneTareas.setViewportView(jPanelTareas);
    }
    
    public VistaPrincipal getjFramePadre() {
        return jFramePadre;
    }

    public void setjFramePadre(VistaPrincipal jFramePadre) {
        this.jFramePadre = jFramePadre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTareas = new javax.swing.JLabel();
        jScrollPaneTareas = new javax.swing.JScrollPane();
        jPanelTareas = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(934, 449));
        setPreferredSize(new java.awt.Dimension(934, 449));

        jLabelTareas.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelTareas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTareas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTareas.setText("Tareas");

        jScrollPaneTareas.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPaneTareas.setBorder(null);
        jScrollPaneTareas.setForeground(new java.awt.Color(204, 204, 204));

        jPanelTareas.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTareas.setForeground(new java.awt.Color(204, 204, 204));
        jPanelTareas.setLayout(new java.awt.GridBagLayout());
        jScrollPaneTareas.setViewportView(jPanelTareas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneTareas)
                    .addComponent(jLabelTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelTareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTareas;
    private javax.swing.JPanel jPanelTareas;
    private javax.swing.JScrollPane jScrollPaneTareas;
    // End of variables declaration//GEN-END:variables
}
