/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 * Contenedor de la tabla proyectos que mostrara toda su información.
 * @author miguelportatil
 */
public class PanelProyectos extends javax.swing.JPanel {

    /**
     * Creates new form PanelProyectos
     */
    VistaPrincipal jFramePadre;
    ModeloTablaProyectos model;
            
    public PanelProyectos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProyectos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProyectos = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(934, 449));
        setPreferredSize(new java.awt.Dimension(934, 449));

        jLabelProyectos.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelProyectos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelProyectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProyectos.setText("Proyectos");

        jTableProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProyectos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelProyectos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProyectos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public VistaPrincipal getjFramePadre() {
        return jFramePadre;
    }

    public void setjFramePadre(VistaPrincipal jFramePadre) {
        this.jFramePadre = jFramePadre;
        model = new ModeloTablaProyectos();
        jTableProyectos.setModel(model);
        refrescarProyectos();
        tamañoJTable();
        
    }
    
    public void tamañoJTable(){
        jTableProyectos.getColumn("DESCRIPCION").setPreferredWidth(350);
        jTableProyectos.getColumn("NOMBRE").setPreferredWidth(30);
        jTableProyectos.getColumn("FECHA INICIO").setPreferredWidth(20);
        jTableProyectos.getColumn("FECHA FIN").setPreferredWidth(20);
        jTableProyectos.getColumn("TAREAS").setPreferredWidth(15);
    }
    
    public void refrescarProyectos(){
        System.out.println(jFramePadre.getTaskTime().getProyectos().size());
        model.refreshTableModel(jFramePadre.getTaskTime());
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProyectos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProyectos;
    // End of variables declaration//GEN-END:variables
}
