/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import util.CRM;
import util.Util;

/**
 * Contenedor que mostrara información básica de un proyecto en concreto el cual
 * podremos elegir
 * 
 * @author miguelportatil
 */
public class PanelProyecto extends javax.swing.JPanel {

    /**
     * Creates new form PanelProyecto
     */
    private VistaPrincipal jFramePadre;
    private int numeroProyectos;
    
    public PanelProyecto() {
        numeroProyectos = 0;
        initComponents();
        jLabelImagen.setVisible(false);
        
    }

    public VistaPrincipal getjFramePadre() {
        return jFramePadre;
    }

    public void setjFramePadre(VistaPrincipal jFramePadre) {
        this.jFramePadre = jFramePadre;
        iniciarJComboBox();  
        iniciarComponentes();
        seleccionarUltimoProyecto();
    }
    
    public void iniciarJComboBox(){
        for (int i = 0; i < jFramePadre.getTaskTime().getProyectos().size(); i++) {
            jComboBoxProyectos.addItem(jFramePadre.getTaskTime().getProyectos().get(i).getNombre());
            numeroProyectos+=1;
        }
        jFramePadre.getTaskTime().setProyectoActivo(numeroProyectos-1);
    }
    
    public void addItemComboBox(String nombre){
        numeroProyectos+=1;
        jComboBoxProyectos.addItem(nombre);
        jFramePadre.getTaskTime().setProyectoActivo(numeroProyectos-1);
    }
    
    private void iniciarComponentes(){
        try{
            if(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getTareas().size()==0){
                jTextFieldFechaInicio.setText(" ---- ");
                jTextFieldFechaFin.setText(" ---- ");
            }else{
                jTextFieldFechaInicio.setText("  "+Util.ft.format(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getFechaInicio()));
                jTextFieldFechaFin.setText("  "+Util.ft.format(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getFechaFin()));
            }
            jLabelTareasResult.setText(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getTareas().size()+"");
       //     imagenProyecto();
            
        }catch(IndexOutOfBoundsException ioobe){
            
        }
    }
    
    /*public void imagenProyecto(){
        try{
            Image img= new ImageIcon(getClass().getResource(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getImagen())).getImage();
            ImageIcon img2=new ImageIcon(img.getScaledInstance(75,75,Image.SCALE_SMOOTH));
            jLabelImagen.setIcon(img2);
        }catch(NullPointerException noe){
            CRM.nuevoMensaje("Hubo problemas al cargar algunas imagen/es del proyecto");
        }
        
    }*/

    public void seleccionarUltimoProyecto() {
        jComboBoxProyectos.setSelectedIndex(jFramePadre.getTaskTime().getProyectoActivo());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProyecto = new javax.swing.JLabel();
        jComboBoxProyectos = new javax.swing.JComboBox<>();
        jLabelFechaInicio = new javax.swing.JLabel();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jLabelFechaFin = new javax.swing.JLabel();
        jTextFieldFechaFin = new javax.swing.JTextField();
        jLabelTareas = new javax.swing.JLabel();
        jLabelTareasResult = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(934, 265));
        setMinimumSize(new java.awt.Dimension(934, 265));
        setPreferredSize(new java.awt.Dimension(934, 265));

        jLabelProyecto.setBackground(new java.awt.Color(0, 0, 0));
        jLabelProyecto.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelProyecto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelProyecto.setText("Proyecto");

        jComboBoxProyectos.setBackground(new java.awt.Color(242, 242, 242));
        jComboBoxProyectos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jComboBoxProyectos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProyectosItemStateChanged(evt);
            }
        });

        jLabelFechaInicio.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFechaInicio.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabelFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFechaInicio.setText("Fecha inicio");

        jTextFieldFechaInicio.setEditable(false);
        jTextFieldFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaInicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldFechaInicio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaInicioActionPerformed(evt);
            }
        });

        jLabelFechaFin.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFechaFin.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabelFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFechaFin.setText("Fecha finalización");

        jTextFieldFechaFin.setEditable(false);
        jTextFieldFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaFin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldFechaFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabelTareas.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTareas.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabelTareas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTareas.setText("Tareas :");

        jLabelTareasResult.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTareasResult.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabelTareasResult.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTareasResult.setText("0");
        jLabelTareasResult.setToolTipText("Total tareas");

        jLabelImagen.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTareas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTareasResult))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelProyecto)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFechaInicio)
                                .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFechaFin)))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabelFechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFechaInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTareas)
                    .addComponent(jLabelTareasResult))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProyectosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProyectosItemStateChanged
        // TODO add your handling code here:
        
        int indice = jComboBoxProyectos.getSelectedIndex();
        jFramePadre.getTaskTime().setProyectoActivo(indice);
        iniciarComponentes();
        jFramePadre.getPanelTareas().limpiarTareas();
        jFramePadre.getPanelTareas().generarTareas();
        
    }//GEN-LAST:event_jComboBoxProyectosItemStateChanged
    
    /*public void cambiarJComboBox(int index){
        jComboBoxProyectos.setSelectedIndex(jComboBoxProyectos);
    }*/
    
    private void jTextFieldFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaInicioActionPerformed

    public JTextField getjTextFieldFechaFin() {
        return jTextFieldFechaFin;
    }

    public void setjTextFieldFechaFin(String cadena) {
        if(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getTareas().size()==0){
            this.jTextFieldFechaFin.setText(" ---- ");
        }
        else{
            this.jTextFieldFechaFin.setText(cadena);
        }
    }

    public JTextField getjTextFieldFechaInicio() {
        return jTextFieldFechaInicio;
    }

    public void setjTextFieldFechaInicio(String cadena) {
        if(jFramePadre.getTaskTime().getProyectos().get(jFramePadre.getTaskTime().getProyectoActivo()).getTareas().size()==0){
            this.jTextFieldFechaInicio.setText(" ---- ");
        }else
            this.jTextFieldFechaInicio.setText(cadena);
    }
    
    public void setTareas(int tareas){
        jLabelTareasResult.setText(""+tareas);
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxProyectos;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelProyecto;
    private javax.swing.JLabel jLabelTareas;
    private javax.swing.JLabel jLabelTareasResult;
    private javax.swing.JTextField jTextFieldFechaFin;
    private javax.swing.JTextField jTextFieldFechaInicio;
    // End of variables declaration//GEN-END:variables
}
